import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="pixel-font antialiased bg-[#101624] text-white min-h-screen"
      >
        {/* Remove all floating boxes for all pages */}
        <nav className="w-full flex items-center justify-between px-8 py-6 border-b-4 border-[#232b45] bg-[#181e34] shadow-lg min-h-[72px]">
          <div className="flex items-center gap-3">
            <span className="text-2xl font-bold tracking-widest pixel-font"> Portfolio</span>
          </div>
          <ul className="flex gap-6 text-base font-mono">
            <li><Link href="/" className="hover:text-yellow-400 transition mt-[6px]">Home</Link></li>
            <li><Link href="/projects" className="hover:text-yellow-400 transition mt-[6px]">Projects</Link></li>
            <li><Link href="/blog" className="hover:text-yellow-400 transition mt-[6px]">Blog</Link></li>
            <li><Link href="/game" className="hover:text-yellow-400 transition mt-[6px]">Game?</Link></li>
            <li><Link href="/#contact" className="hover:text-yellow-400 transition mt-[6px]">Contact</Link></li>
            <li><Link href="/profile" className="hover:text-yellow-400 transition mt-[6px]">Profile</Link></li>
          </ul>
        </nav>
        <main className="w-full px-2">
          {children}
        </main>
        <footer className="w-full bg-[#181e34] border-t-4 border-[#232b45] py-4 mt-8 flex flex-col items-center justify-center text-gray-300 text-sm">
          <span>&copy; {new Date().getFullYear()} Harshitha Salian. All rights reserved.</span>
          <a href="#" className="text-yellow-400 underline hover:text-yellow-300 mt-1">Terms &amp; Conditions</a>
        </footer>
      </body>
    </html>
  );
}
